# Generated by Django 4.2.30 on 2026-04-20 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="User's question or message")),
                ('response', models.TextField(help_text='AI-generated response')),
                ('category', models.CharField(choices=[('expense_cutting', 'Expense Optimization'), ('investment', 'Investment Advice'), ('budget', 'Budget Help'), ('emi_help', 'EMI & Loans'), ('savings', 'Savings Tips'), ('general', 'General Question')], default='general', max_length=20)),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_chatme_user_id_c2f6a2_idx'), models.Index(fields=['category'], name='core_chatme_categor_10cffe_idx')],
            },
        ),
    ]
